language: node_js

sudo: required
dist: trusty

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install --pure-lockfile --force

script:
  - npm run lint
  - npm run build
  - npm run test -- --coverage
